Add: Device manager
bluerobotics/ping-viewer-next pull request #2
Opened 2024-06-04 19:27 UTC by RaulTrombin

This PR adds DeviceManager and Device modules, each following the actor pattern.
Each structure has its own handler, allowing usage across multiple and different threads.

Device requests made to the Manager are forwarded directly to the respective Device. Each request provides a Result<Answer, ManagerError>.

Requires merge&bump on ping-rs: 
- [x] https://github.com/bluerobotics/ping-rs/pull/52

some cool refs:
https://ryhl.io/blog/actors-with-tokio/
https://theari.dev/blog/tokio-actors/
https://www.oreilly.com/library/view/applied-akka-patterns/9781491934876/ch01.html
https://www.amazon.com/Rust-Web-Programming-hands-applications/dp/1803234695

2024-07-17 16:18 UTC, patrickelectric requested changes

2024-07-17 16:18 UTC, patrickelectric commented on src/device/devices.rs
> +            },
```suggestion
            PingRequest::Ping1D(device_request) | PingRequest::Ping360(device_request) | PingRequest::Common(device_request) => match &self.device_type {
                DeviceType::Ping1D(device) | DeviceType::Ping360(device) | DeviceType::Common(device) => {
                    let answer = device.handle(device_request).await;
                    let _ = request.respond_to.send(DeviceActorAnswer { answer });
                }
                _ => {
                    let ping_request = request.request;
                    let _ = request.respond_to.send(DeviceActorAnswer {
                        answer: PingAnswer::NotSupported(ping_request),
                    });
                }
            },
```

2024-07-17 16:18 UTC, patrickelectric commented on src/device/devices.rs
> +            DeviceType::Ping1D(device) => {
We should only deal with common case, the others are already upgraded.

2024-07-17 16:18 UTC, patrickelectric commented on src/device/manager.rs
> +        };
You should match port first and than the device.

2024-07-18 14:01 UTC, RaulTrombin commented on src/device/devices.rs
> +            DeviceType::Ping1D(device) => {
the function was designed to:
If they already belong to the upgrading available class, they'll return quickly; 
if not, they'll be repaired in the next step.

If it is not dealt with, we will remove this functionality.

2024-07-18 14:01 UTC, RaulTrombin commented on src/device/manager.rs
> +        };
did it.

2024-07-18 14:02 UTC, RaulTrombin commented on src/device/manager.rs
> +    Other,
removed this error for now, was  used on only one place with and unreachable  case.

2024-07-18 14:20 UTC, RaulTrombin commented on src/device/devices.rs
> +            },
i'll require some manipulation on strings, custom input for return type and different handling for methods.
But'll help to make to code more cleanner, can we add as an future upgrade?

2024-07-18 15:37 UTC, RaulTrombin commented on src/device/devices.rs
> +            },
Different devices and requests types 
```
error[E0308]: mismatched types
  --> src/device/devices.rs:20:72
   |
19 |         match request.request.clone() {
   |               ----------------------- this expression has type `PingRequest`
20 |             PingRequest::Ping1D(device_request) | PingRequest::Ping360(device_request) | PingRequest::Common(device_request) => match &self.device_type {
   |                                 --------------                         ^^^^^^^^^^^^^^ expected `Ping1DRequest`, found `Ping360Request`
   |                                 |
   |                                 first introduced with type `Ping1DRequest` here
   |
   = note: in the same arm, a binding must have the same type in all alternatives

error[E0308]: mismatched types
  --> src/device/devices.rs:20:110
   |
19 |         match request.request.clone() {
   |               ----------------------- this expression has type `PingRequest`
20 |             PingRequest::Ping1D(device_request) | PingRequest::Ping360(device_request) | PingRequest::Common(device_request) => match &self.device_type {
   |                                 -------------- first introduced with type `Ping1DRequest` here               ^^^^^^^^^^^^^^ expected `Ping1DRequest`, found `PingCommonRequest`
   |
   = note: in the same arm, a binding must have the same type in all alternatives

error[E0308]: mismatched types
  --> src/device/devices.rs:21:66
   |
20 |             PingRequest::Ping1D(device_request) | PingRequest::Ping360(device_request) | PingRequest::Common(device_request) => match &self.device_type {
   |                                                                                                                                       ----------------- this expression has type `&DeviceType`
21 |                 DeviceType::Ping1D(device) | DeviceType::Ping360(device) | DeviceType::Common(device) => {
   |                                    ------                        ^^^^^^ expected `&Ping1D`, found `&Ping360`
   |                                    |
   |                                    first introduced with type `&bluerobotics_ping::device::Ping1D` here
   |
   = note: expected reference `&bluerobotics_ping::device::Ping1D`
              found reference `&bluerobotics_ping::device::Ping360`
   = note: in the same arm, a binding must have the same type in all alternatives

error[E0308]: mismatched types
  --> src/device/devices.rs:21:95
   |
20 |             PingRequest::Ping1D(device_request) | PingRequest::Ping360(device_request) | PingRequest::Common(device_request) => match &self.device_type {
   |                                                                                                                                       ----------------- this expression has type `&DeviceType`
21 |                 DeviceType::Ping1D(device) | DeviceType::Ping360(device) | DeviceType::Common(device) => {
   |                                    ------                                                     ^^^^^^ expected `&Ping1D`, found `&Device`
   |                                    |
   |                                    first introduced with type `&bluerobotics_ping::device::Ping1D` here
   |
   = note: expected reference `&bluerobotics_ping::device::Ping1D`
              found reference `&bluerobotics_ping::common::Device`
   = note: in the same arm, a binding must have the same type in all alternatives

For more information about this error, try `rustc --explain E0308`.
warning: `ping-viewer-next` (bin "ping-viewer-next") generated 1 warning
error: could not compile `ping-viewer-next` (bin "ping-viewer-next") due to 4 previous errors; 1 warning emitted
```

2024-07-18 15:38 UTC, RaulTrombin commented on src/device/devices.rs
> +            },
Different devices and requests types :-/ 
Please check above:
> 
> ```
> error[E0308]: mismatched types
>   --> src/device/devices.rs:20:72
>    |
> 19 |         match request.request.clone() {
>    |               ----------------------- this expression has type `PingRequest`
> 20 |             PingRequest::Ping1D(device_request) | PingRequest::Ping360(device_request) | PingRequest::Common(device_request) => match &self.device_type {
>    |                                 --------------                         ^^^^^^^^^^^^^^ expected `Ping1DRequest`, found `Ping360Request`
>    |                                 |
>    |                                 first introduced with type `Ping1DRequest` here
>    |
>    = note: in the same arm, a binding must have the same type in all alternatives
> 
> error[E0308]: mismatched types
>   --> src/device/devices.rs:20:110
>    |
> 19 |         match request.request.clone() {
>    |               ----------------------- this expression has type `PingRequest`
> 20 |             PingRequest::Ping1D(device_request) | PingRequest::Ping360(device_request) | PingRequest::Common(device_request) => match &self.device_type {
>    |                                 -------------- first introduced with type `Ping1DRequest` here               ^^^^^^^^^^^^^^ expected `Ping1DRequest`, found `PingCommonRequest`
>    |
>    = note: in the same arm, a binding must have the same type in all alternatives
> 
> error[E0308]: mismatched types
>   --> src/device/devices.rs:21:66
>    |
> 20 |             PingRequest::Ping1D(device_request) | PingRequest::Ping360(device_request) | PingRequest::Common(device_request) => match &self.device_type {
>    |                                                                                                                                       ----------------- this expression has type `&DeviceType`
> 21 |                 DeviceType::Ping1D(device) | DeviceType::Ping360(device) | DeviceType::Common(device) => {
>    |                                    ------                        ^^^^^^ expected `&Ping1D`, found `&Ping360`
>    |                                    |
>    |                                    first introduced with type `&bluerobotics_ping::device::Ping1D` here
>    |
>    = note: expected reference `&bluerobotics_ping::device::Ping1D`
>               found reference `&bluerobotics_ping::device::Ping360`
>    = note: in the same arm, a binding must have the same type in all alternatives
> 
> error[E0308]: mismatched types
>   --> src/device/devices.rs:21:95
>    |
> 20 |             PingRequest::Ping1D(device_request) | PingRequest::Ping360(device_request) | PingRequest::Common(device_request) => match &self.device_type {
>    |                                                                                                                                       ----------------- this expression has type `&DeviceType`
> 21 |                 DeviceType::Ping1D(device) | DeviceType::Ping360(device) | DeviceType::Common(device) => {
>    |                                    ------                                                     ^^^^^^ expected `&Ping1D`, found `&Device`
>    |                                    |
>    |                                    first introduced with type `&bluerobotics_ping::device::Ping1D` here
>    |
>    = note: expected reference `&bluerobotics_ping::device::Ping1D`
>               found reference `&bluerobotics_ping::common::Device`
>    = note: in the same arm, a binding must have the same type in all alternatives
> 
> For more information about this error, try `rustc --explain E0308`.
> warning: `ping-viewer-next` (bin "ping-viewer-next") generated 1 warning
> error: could not compile `ping-viewer-next` (bin "ping-viewer-next") due to 4 previous errors; 1 warning emitted
> ```



> ping @RaulTrombin

2024-07-18 19:58 UTC, patrickelectric approved these changes

2024-07-18 19:58 UTC, merged