Add: Dekstop-app
bluerobotics/ping-viewer-next pull request #21
Opened 2024-09-11 17:51 UTC by RaulTrombin

2024-09-24 13:14 UTC, patrickelectric commented on .github/workflows/action.yml
> +                - platform: 'macos-latest' # for Arm based macs (M1 and above).
Keep in mind that macos-13 is for Intel and macos-14/macos-latest is for ARM.

2024-09-24 21:58 UTC, RaulTrombin commented on .github/workflows/action.yml
> +                - platform: 'macos-latest' # for Arm based macs (M1 and above).
bellow there is the args prop,
```
                - platform: 'macos-latest' # for Arm based macs (M1 and above).
                  args: '--target aarch64-apple-darwin'
                - platform: 'macos-latest' # for Intel based macs.
                  args: '--target x86_64-apple-darwin'
```

2024-09-26 16:23 UTC, patrickelectric requested changes

2024-09-26 16:23 UTC, patrickelectric commented on ping-viewer-next-desktop/.gitignore
> +# Logs
This is not necessary, can we clean it up ?

2024-09-26 16:23 UTC, patrickelectric commented on ping-viewer-next-desktop/src-tauri/Cargo.toml
> +authors = ["you"]
Missing authors

2024-09-26 16:31 UTC, RaulTrombin commented on ping-viewer-next-desktop/.gitignore
> +# Logs
this is the Logs default folder when we execute the desktop app with logger module, would suggest to keep it

2024-10-01 13:38 UTC, patrickelectric commented on ping-viewer-next-desktop/.gitignore
> +# Logs
I'm just saying to remove the unnecessary stuff, .idea, .dist-ssr, .sln

2024-10-01 13:39 UTC, patrickelectric requested changes

2024-10-01 13:39 UTC, patrickelectric commented on .github/workflows/action.yml
> +                retention-days: 5
Missing EOL

2024-10-03 14:22 UTC, RaulTrombin commented on .github/workflows/action.yml
> +                  label: 'Mac-M1'
@patrickelectric

2024-10-07 17:33 UTC, patrickelectric approved these changes

2024-10-07 17:34 UTC, merged