Add : gh actions linter checkings
bluerobotics/ping-viewer-next pull request #3
Opened 2024-06-04 19:33 UTC by RaulTrombin

2024-06-04 19:46 UTC, joaoantoniocardoso requested changes
these tools from `actions-rs/toolchain` are unmaintained and deprecated. I recently updated MCM CI: checkout it [here](https://github.com/mavlink/mavlink-camera-manager/tree/t3.13.0/.github/workflows)

2024-06-04 20:38 UTC, RaulTrombin commented
> these tools from `actions-rs/toolchain` are unmaintained and deprecated. I recently updated MCM's CI: checkout it [here](https://github.com/mavlink/mavlink-camera-manager/tree/t3.13.0/.github/workflows)

Did it, Seems ok : 
https://github.com/RaulTrombin/ping-viewer-next/actions/runs/9373871074/job/25808599455

2024-06-04 20:59 UTC, patrickelectric approved these changes

2024-06-06 14:46 UTC, joaoantoniocardoso approved these changes

2024-06-06 14:46 UTC, merged