Add: Enable/Disable Broadcast for Ping1D profile through websocket.
bluerobotics/ping-viewer-next pull request #7
Opened 2024-07-19 23:52 UTC by RaulTrombin

2024-07-31 21:26 UTC, joaoantoniocardoso reviewed
Cool code! Things to think about:

1. naming: we are here calling _boardcast_ as a proxy word for a behavior that is called _continuous_ elsewhere, it sounds confusing, also because _broadcast_ usually means _send to everyone a the same time_.
2. log level: trace usually requires the user to run the application enabling trace log level, and some failures are only being shown there, so it will fail and the user will have no idea, and when we'll read the logs, we will also have no clue why it failed, and then we'll have to ask the user to run a different command....

2024-07-31 21:26 UTC, joaoantoniocardoso commented on src/device/manager.rs
> +    // Series of inner helpers specially for broadcast methods
This comment seems kinda lost in the code. You can split your implementations into two or more separate impl blocks if you think it is useful for organization, like having all broadcasting-related functions into one impl block apart from the rest.

2024-07-31 21:26 UTC, joaoantoniocardoso commented on src/device/manager.rs
> +                            handler.send(super::devices::PingRequest::Ping360(
Unless it is used somewhere else, the code below is also easy to follow and doesn't require us to keep the variable/value in the mind:
```Diff
---                let timeout: u64 = 1000;
                loop {
                    for n in 0..399 {
                        // Handle timeout and errors
                        let result = tokio::time::timeout(
---                            timeout,
+++                            std::time::Duration::from_millis(1000),
                            handler.send(super::devices::PingRequest::Ping360(
```

2024-07-31 21:26 UTC, joaoantoniocardoso commented on src/device/manager.rs
> +                    for n in 0..399 {
why 399?

2024-07-31 21:26 UTC, joaoantoniocardoso commented on src/device/manager.rs
> +                                trace!("Error during broadcasting: Answer delayed more than {timeout} ms");
Wouldn't this be useful to know when this happens?
If `never`, then trace is okay
if `maybe`, then it should be a debug
if it is important for the final user, it should be a warning or an error

2024-07-31 21:26 UTC, joaoantoniocardoso commented on src/device/manager.rs
> +    }
Shouldn't these functions be public?

2024-07-31 21:26 UTC, joaoantoniocardoso commented on src/device/manager.rs
> +                trace!("Something went wrong while executing get_subscriber, details: {err:?}");
trace or error/warn?

2024-08-01 00:24 UTC, RaulTrombin commented on src/device/manager.rs
> +                    for n in 0..399 {
https://docs.bluerobotics.com/ping-protocol/pingmessage-ping360/#2601-transducer
u16	angle	Head angle	gradians

2024-08-01 00:26 UTC, RaulTrombin commented on src/device/manager.rs
> +                                trace!("Error during broadcasting: Answer delayed more than {timeout} ms");
I think a warn fits well

2024-08-01 00:27 UTC, RaulTrombin commented on src/device/manager.rs
> +    }
they can, but until now it's only used by strucutre, 
should I upgrade it?

2024-08-01 00:28 UTC, RaulTrombin commented on src/device/manager.rs
> +                trace!("Something went wrong while executing get_subscriber, details: {err:?}");
warn

2024-08-01 00:29 UTC, RaulTrombin commented on src/device/manager.rs
> +    }
I'm going to upgrade to public methods

2024-08-05 22:40 UTC, joaoantoniocardoso approved these changes
just minors

2024-08-05 22:40 UTC, joaoantoniocardoso commented on src/device/manager.rs
> +        );
```diff
        error!(
---            "Getting device handler for device: {:?} : Error, device doesn't exist",
---            device_id
---        );
+++            "Getting device handler for device: {device_id:?} : Error, device doesn't exist");
```

2024-08-05 22:40 UTC, joaoantoniocardoso commented on src/device/manager.rs
> +        );
```diff
        trace!(
---            "Getting device handler for device: {:?} : Success",
---            device_id
---        );
+++            "Getting device handler for device: {device_id:?} : Success");
```

2024-08-05 22:40 UTC, joaoantoniocardoso commented on src/device/manager.rs
> +                    );
`{e:?}` here too

2024-08-05 22:40 UTC, joaoantoniocardoso commented on src/device/manager.rs
> +                    );
`{e:?}` here too

2024-08-05 22:40 UTC, joaoantoniocardoso commented on src/device/manager.rs
> +                trace!("Device delete id {:?}: Success", device_id);
`{device_id:?}` here too

2024-08-05 22:42 UTC, joaoantoniocardoso requested changes
oops, different commits are changing the same lines. Can you try to fix it?

2024-08-06 01:19 UTC, RaulTrombin commented
> oops, different commits are changing the same lines. Can you try to fix it?

Done

2024-08-06 03:46 UTC, joaoantoniocardoso approved these changes

2024-08-06 03:46 UTC, merged